// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/tosuke/opentelemetry-collector-components/processor/downsamplingprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/tosuke/opentelemetry-collector-components/processor/downsamplingprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                         metric.Meter
	mu                                            sync.Mutex
	registrations                                 []metric.Registration
	ProcessorDownsamplingCardinality              metric.Int64ObservableGauge
	ProcessorDownsamplingCardinalityExceededItems metric.Int64ObservableCounter
	ProcessorDownsamplingCardinalityLimit         metric.Int64ObservableGauge
	ProcessorIncomingItems                        metric.Int64Counter
	ProcessorOutgoingItems                        metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// RegisterProcessorDownsamplingCardinalityCallback sets callback for observable ProcessorDownsamplingCardinality metric.
func (builder *TelemetryBuilder) RegisterProcessorDownsamplingCardinalityCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorDownsamplingCardinality, obs: o})
		return nil
	}, builder.ProcessorDownsamplingCardinality)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorDownsamplingCardinalityExceededItemsCallback sets callback for observable ProcessorDownsamplingCardinalityExceededItems metric.
func (builder *TelemetryBuilder) RegisterProcessorDownsamplingCardinalityExceededItemsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorDownsamplingCardinalityExceededItems, obs: o})
		return nil
	}, builder.ProcessorDownsamplingCardinalityExceededItems)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorDownsamplingCardinalityLimitCallback sets callback for observable ProcessorDownsamplingCardinalityLimit metric.
func (builder *TelemetryBuilder) RegisterProcessorDownsamplingCardinalityLimitCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorDownsamplingCardinalityLimit, obs: o})
		return nil
	}, builder.ProcessorDownsamplingCardinalityLimit)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

type observerInt64 struct {
	embedded.Int64Observer
	inst metric.Int64Observable
	obs  metric.Observer
}

func (oi *observerInt64) Observe(value int64, opts ...metric.ObserveOption) {
	oi.obs.ObserveInt64(oi.inst, value, opts...)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ProcessorDownsamplingCardinality, err = builder.meter.Int64ObservableGauge(
		"otelcol_processor_downsampling_cardinality",
		metric.WithDescription("The current number of unique keys being processed. [development]"),
		metric.WithUnit("{items}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorDownsamplingCardinalityExceededItems, err = builder.meter.Int64ObservableCounter(
		"otelcol_processor_downsampling_cardinality_exceeded_items",
		metric.WithDescription("The total number of items that exceeded the cardinality limit. [development]"),
		metric.WithUnit("{items}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorDownsamplingCardinalityLimit, err = builder.meter.Int64ObservableGauge(
		"otelcol_processor_downsampling_cardinality_limit",
		metric.WithDescription("The maximum number of unique keys allowed in the processor. [development]"),
		metric.WithUnit("{items}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorIncomingItems, err = builder.meter.Int64Counter(
		"otelcol_processor_incoming_items",
		metric.WithDescription("The total number of items received by the processor. [development]"),
		metric.WithUnit("{items}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorOutgoingItems, err = builder.meter.Int64Counter(
		"otelcol_processor_outgoing_items",
		metric.WithDescription("The total number of items emitted by the processor. [development]"),
		metric.WithUnit("{items}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
