// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("downsampling")
	ScopeName = "github.com/tosuke/opentelemetry-collector-components/processor/downsamplingprocessor"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
